### PR TITLE
fix: no default axis hooks bug

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**
closes : https://github.com/zakodium-oss/react-plot/issues/423

### CODE REVIEW

**Comment by targos** [comment]
Do we already have a story with this case? If not, can you add one?

**Comment by wadjih-bencheikh18** [comment]
> Do we already have a story with this case? If not, can you add one?

the problem is in https://github.com/zakodium-oss/analysis-ui-components/pull/166

https://deploy-preview-166--analysis-ui-components.netlify.app/storybook/?path=/story/layout-measurementexplorer--control choose xVariable : "t"

**Comment by wadjih-bencheikh18** [comment]
i will try to create a story with the problem

**Comment by wadjih-bencheikh18** [comment]
@targos story added

**Comment by targos** [comment]
How can I reproduce the problem with the story? I tried to add a log when the value is `undefined` but nothing happens.

**Comment by targos** [comment]
I think it would be better to show the bug with a very simple story instead of this one.

**Comment by wadjih-bencheikh18** [comment]
> I think it would be better to show the bug with a very simple story instead of this one.

the problem happend while changing the data after the plot loaded so i added a story where u can change horizantal and vertical variables

**Comment by wadjih-bencheikh18** [comment]
the bug always happend if we revert this modification https://github.com/zakodium-oss/react-plot/pull/424/commits/2aac5826cb1cd4373d0c2cfe1eafccc6709185b4

**Comment by targos** [comment]
But for me this is not the correct fix. The crosshair doesn't work as expected.

**Comment by wadjih-bencheikh18** [comment]
@targos i found the problem and fix it 
the thing that hooks were not genralized to use with no default axis variables

also i added DualAxisOptions in useAxisZoom to fix the problem

**Comment by targos** [comment]
Vertical zoom doesn't work (it's horizontal), but apart from that, good job! 
https://deploy-preview-424--react-plot.netlify.app/?path=/story/examples-measurement--measurement&args=xAxis:a;yAxis:t;hook:Vertical+Zoom

**Comment by wadjih-bencheikh18** [comment]
> Vertical zoom doesn't work (it's horizontal)

Sorry about that , it's fixed now

**Pull request merged**
