### PR TITLE
fix: FunctionSeries

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**
closes : https://github.com/zakodium-oss/react-plot/issues/377
closes :  https://github.com/zakodium-oss/react-plot/issues/378
fixes : https://github.com/zakodium-oss/react-plot/issues/379
closes : https://github.com/zakodium-oss/react-plot/issues/385

### CODE REVIEW

**Comment by wadjih-bencheikh18** [comment]
The problem now with `FunctionSeries` after these changes is we have to specifie max,min of vertical axis too

**Implementation detail:**
how FunctionSeries work?
it take max/ min from horizantal axis if this latter exist and draw lineSeries in [min, max] domain

to specifie max / min we need to either:
- axis max, min props
- or add another series => axis will calculate automatically max, min

=> logically we need just to specifie max /min of horizontal axis to draw it .
but the problem is When Plot is empty 
```
<Plot {...DEFAULT_PLOT_CONFIG}>
      <FunctionSeries
        getY={getY}
      />
      <Axis
        min={0}
        max={20}
        position="bottom"
      />
      <Axis position="left"/>
</Plot>
```
 => vertical axis domain is not defined => no horizantal axis

image

**Comment by targos** [comment]
I hope the above will also be fixed with https://github.com/zakodium-oss/react-plot/issues/316

**Comment by targos** [comment]
The new story updates infinitely and crashes. Is that expected?

**Comment by wadjih-bencheikh18** [comment]
here i made simple solution but not the best ,
i just added ~ in functionSeries id so it won't be considered while calculating Max, Min

**Pull request merged**
