### PR TITLE
Disabled hooks

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**
closes : https://github.com/zakodium-oss/react-plot/issues/417

### CODE REVIEW

**Comment by wadjih-bencheikh18** [comment]
@targos i added disabled param in hooks stories
 https://deploy-preview-421--react-plot.netlify.app/?path=/story/examples-draw--draw-path
 https://deploy-preview-421--react-plot.netlify.app/?path=/story/examples-lasso-selection--lasso-selection
 https://deploy-preview-421--react-plot.netlify.app/?path=/story/examples-spectrum-2d--spectrum-2-d
 https://deploy-preview-421--react-plot.netlify.app/?path=/story/examples-zoom--horizontal-zoom
 https://deploy-preview-421--react-plot.netlify.app/?path=/story/experimental-spectra-infrared--infrared-example
 https://deploy-preview-421--react-plot.netlify.app/?path=/story/experimental-spectra-mass--advanced-mass-example

**Comment by targos** [comment]
why do you open/close many PRs for the same change?

**Comment by wadjih-bencheikh18** [comment]
> why do you open/close many PRs for the same change?

I closed the issue because of bad commit message (I used break changes option and it's not the case here), sorry for that

**Comment by targos** [comment]
Ah, for next time you can use `git push --force` to update the PR without the need to create a new branch and PR.

**Pull request merged**
